name: evolve
channels:
  - defaults
dependencies:
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.12.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.4.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvmlite=0.39.1
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pygments=2.11.2
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pytest=7.1.2
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.7
  - pywin32=305
  - pyzmq=23.2.0
  - seaborn=0.12.2
  - setuptools=65.6.3
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tbb=2021.6.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - appdirs==1.4.4
    - importlib-metadata==6.0.0
    - memory-profiler==0.61.0
    - pyee==8.2.2
    - pyppeteer==1.0.2
    - tqdm==4.64.1
    - urllib3==1.26.14
    - zipp==3.13.0
